// Built-in fragrance-note icon library. Images live in /public/notes/<slug>.webp.
// Admin-uploaded custom icons (from /api/notes) take precedence by note name.

export const NOTE_LIBRARY: { slug: string; name: string }[] = [
  { slug: 'abstract-accord', name: 'Abstract Accord' },
  { slug: 'air-accord', name: 'Air Accord' },
  { slug: 'akigalawood', name: 'Akigalawood' },
  { slug: 'aldehydes', name: 'Aldehydes' },
  { slug: 'almond', name: 'Almond' },
  { slug: 'amber', name: 'Amber' },
  { slug: 'ambergris', name: 'Ambergris' },
  { slug: 'amberwood', name: 'Amberwood' },
  { slug: 'ambrette-seed', name: 'Ambrette Seed' },
  { slug: 'ambroxan', name: 'Ambroxan' },
  { slug: 'amyris', name: 'Amyris' },
  { slug: 'angelica', name: 'Angelica' },
  { slug: 'animalic-musk', name: 'Animalic Musk' },
  { slug: 'animalis', name: 'Animalis' },
  { slug: 'apple', name: 'Apple' },
  { slug: 'apricot', name: 'Apricot' },
  { slug: 'aquatic-notes', name: 'Aquatic Notes' },
  { slug: 'artemisia', name: 'Artemisia' },
  { slug: 'asphalt', name: 'Asphalt' },
  { slug: 'australian-sandalwood', name: 'Australian Sandalwood' },
  { slug: 'bamboo', name: 'Bamboo' },
  { slug: 'banana', name: 'Banana' },
  { slug: 'basil', name: 'Basil' },
  { slug: 'bay-saint-thomas', name: 'Bay Saint Thomas' },
  { slug: 'beer', name: 'Beer' },
  { slug: 'beeswax', name: 'Beeswax' },
  { slug: 'beetroot', name: 'Beetroot' },
  { slug: 'bell-pepper', name: 'Bell Pepper' },
  { slug: 'benzoin', name: 'Benzoin' },
  { slug: 'bergamot', name: 'Bergamot' },
  { slug: 'berry-notes', name: 'Berry Notes' },
  { slug: 'birch', name: 'Birch' },
  { slug: 'birch-tar', name: 'Birch Tar' },
  { slug: 'bitter-orange', name: 'Bitter Orange' },
  { slug: 'black-amber', name: 'Black Amber' },
  { slug: 'black-pepper', name: 'Black Pepper' },
  { slug: 'black-tea', name: 'Black Tea' },
  { slug: 'blackberry', name: 'Blackberry' },
  { slug: 'blackcurrant', name: 'Blackcurrant' },
  { slug: 'blond-woods', name: 'Blond Woods' },
  { slug: 'blood', name: 'Blood' },
  { slug: 'blood-orange', name: 'Blood Orange' },
  { slug: 'blue-tea', name: 'Blue Tea' },
  { slug: 'bluebell', name: 'Bluebell' },
  { slug: 'blueberry', name: 'Blueberry' },
  { slug: 'bourbon', name: 'Bourbon' },
  { slug: 'bourbon-vanilla', name: 'Bourbon Vanilla' },
  { slug: 'bourbon-vetiver', name: 'Bourbon Vetiver' },
  { slug: 'brazilian-rosewood', name: 'Brazilian Rosewood' },
  { slug: 'broom', name: 'Broom' },
  { slug: 'bulgarian-rose', name: 'Bulgarian Rose' },
  { slug: 'butterscotch', name: 'Butterscotch' },
  { slug: 'cabreuva', name: 'Cabreuva' },
  { slug: 'cacao', name: 'Cacao' },
  { slug: 'cade', name: 'Cade' },
  { slug: 'calabrian-bergamot', name: 'Calabrian Bergamot' },
  { slug: 'calone', name: 'Calone' },
  { slug: 'cambodian-oud', name: 'Cambodian Oud' },
  { slug: 'cannabis', name: 'Cannabis' },
  { slug: 'caramel', name: 'Caramel' },
  { slug: 'caraway', name: 'Caraway' },
  { slug: 'cardamom', name: 'Cardamom' },
  { slug: 'carnation', name: 'Carnation' },
  { slug: 'carrot', name: 'Carrot' },
  { slug: 'carrot-seed', name: 'Carrot Seed' },
  { slug: 'cascarilla-bark', name: 'Cascarilla Bark' },
  { slug: 'cashmeran', name: 'Cashmeran' },
  { slug: 'cashmere-musk', name: 'Cashmere Musk' },
  { slug: 'cashmere-wood', name: 'Cashmere Wood' },
  { slug: 'castoreum', name: 'Castoreum' },
  { slug: 'cedar', name: 'Cedar' },
  { slug: 'centifolia-rose', name: 'Centifolia Rose' },
  { slug: 'cereal-notes', name: 'Cereal Notes' },
  { slug: 'cetalox', name: 'Cetalox' },
  { slug: 'chamomile', name: 'Chamomile' },
  { slug: 'champaca', name: 'Champaca' },
  { slug: 'cherry', name: 'Cherry' },
  { slug: 'cherry-blossom', name: 'Cherry Blossom' },
  { slug: 'chestnut', name: 'Chestnut' },
  { slug: 'chocolate', name: 'Chocolate' },
  { slug: 'cinnamon', name: 'Cinnamon' },
  { slug: 'cistus-labdanum', name: 'Cistus Labdanum' },
  { slug: 'citric-notes', name: 'Citric Notes' },
  { slug: 'civet', name: 'Civet' },
  { slug: 'civettone', name: 'Civettone' },
  { slug: 'clary-sage', name: 'Clary Sage' },
  { slug: 'clean-laundry', name: 'Clean Laundry' },
  { slug: 'clearwood', name: 'Clearwood' },
  { slug: 'clove', name: 'Clove' },
  { slug: 'coconut', name: 'Coconut' },
  { slug: 'coffee', name: 'Coffee' },
  { slug: 'cognac', name: 'Cognac' },
  { slug: 'cola', name: 'Cola' },
  { slug: 'copaiba-balsam', name: 'Copaiba Balsam' },
  { slug: 'copal', name: 'Copal' },
  { slug: 'coriander', name: 'Coriander' },
  { slug: 'coriander-seed', name: 'Coriander Seed' },
  { slug: 'cotton-candy', name: 'Cotton Candy' },
  { slug: 'coumarin', name: 'Coumarin' },
  { slug: 'cranberry', name: 'Cranberry' },
  { slug: 'cream', name: 'Cream' },
  { slug: 'cubeb', name: 'Cubeb' },
  { slug: 'cucumber', name: 'Cucumber' },
  { slug: 'cumin', name: 'Cumin' },
  { slug: 'cyclamen', name: 'Cyclamen' },
  { slug: 'cypress', name: 'Cypress' },
  { slug: 'cypress-root', name: 'Cypress Root' },
  { slug: 'cypriol', name: 'Cypriol' },
  { slug: 'dark-patchouli', name: 'Dark Patchouli' },
  { slug: 'date', name: 'Date' },
  { slug: 'davana', name: 'Davana' },
  { slug: 'dihydromyrcenol', name: 'Dihydromyrcenol' },
  { slug: 'dried-fruits', name: 'Dried Fruits' },
  { slug: 'dry-woods', name: 'Dry Woods' },
  { slug: 'ebony-wood', name: 'Ebony Wood' },
  { slug: 'edelweiss', name: 'Edelweiss' },
  { slug: 'elderflower', name: 'Elderflower' },
  { slug: 'elemi', name: 'Elemi' },
  { slug: 'elm-leaf', name: 'Elm-Leaf' },
  { slug: 'english-lavender', name: 'English Lavender' },
  { slug: 'eucalyptus', name: 'Eucalyptus' },
  { slug: 'fern', name: 'Fern' },
  { slug: 'fig', name: 'Fig' },
  { slug: 'fig-leaf', name: 'Fig Leaf' },
  { slug: 'fir', name: 'Fir' },
  { slug: 'fir-balsam', name: 'Fir Balsam' },
  { slug: 'floral-notes', name: 'Floral Notes' },
  { slug: 'frangipani', name: 'Frangipani' },
  { slug: 'freesia', name: 'Freesia' },
  { slug: 'french-lavender', name: 'French Lavender' },
  { slug: 'fruity-notes', name: 'Fruity Notes' },
  { slug: 'galbanum', name: 'Galbanum' },
  { slug: 'gardenia', name: 'Gardenia' },
  { slug: 'georgywood', name: 'Georgywood' },
  { slug: 'geranium', name: 'Geranium' },
  { slug: 'geranium-leaf', name: 'Geranium Leaf' },
  { slug: 'gin', name: 'Gin' },
  { slug: 'ginger', name: 'Ginger' },
  { slug: 'gooseberry', name: 'Gooseberry' },
  { slug: 'gourmand-notes', name: 'Gourmand Notes' },
  { slug: 'grape', name: 'Grape' },
  { slug: 'grapefruit', name: 'Grapefruit' },
  { slug: 'grass', name: 'Grass' },
  { slug: 'green-leaf', name: 'Green Leaf' },
  { slug: 'green-notes', name: 'Green Notes' },
  { slug: 'green-tea', name: 'Green Tea' },
  { slug: 'grey-amber', name: 'Grey Amber' },
  { slug: 'guaiac-wood', name: 'Guaiac Wood' },
  { slug: 'guava', name: 'Guava' },
  { slug: 'gunpowder', name: 'Gunpowder' },
  { slug: 'gurjum', name: 'Gurjum' },
  { slug: 'gurjum-balsam', name: 'Gurjum Balsam' },
  { slug: 'haitian-vetiver', name: 'Haitian Vetiver' },
  { slug: 'hawthorn', name: 'Hawthorn' },
  { slug: 'hay', name: 'Hay' },
  { slug: 'hazelnut', name: 'Hazelnut' },
  { slug: 'hedione', name: 'Hedione' },
  { slug: 'heliotrope', name: 'Heliotrope' },
  { slug: 'helvetolide', name: 'Helvetolide' },
  { slug: 'herbal-notes', name: 'Herbal Notes' },
  { slug: 'hibiscus', name: 'Hibiscus' },
  { slug: 'himalayan-cedar', name: 'Himalayan Cedar' },
  { slug: 'hinoki-wood', name: 'Hinoki Wood' },
  { slug: 'honey', name: 'Honey' },
  { slug: 'honeysuckle', name: 'Honeysuckle' },
  { slug: 'hyacinth', name: 'Hyacinth' },
  { slug: 'immortelle', name: 'Immortelle' },
  { slug: 'incense', name: 'Incense' },
  { slug: 'indian-oud', name: 'Indian Oud' },
  { slug: 'indole', name: 'Indole' },
  { slug: 'indonesian-patchouli', name: 'Indonesian Patchouli' },
  { slug: 'ink', name: 'Ink' },
  { slug: 'iris', name: 'Iris' },
  { slug: 'iso-e-super', name: 'Iso E Super' },
  { slug: 'jasmine', name: 'Jasmine' },
  { slug: 'jasmine-grandiflorum', name: 'Jasmine Grandiflorum' },
  { slug: 'jasmine-sambac', name: 'Jasmine Sambac' },
  { slug: 'java-vetiver', name: 'Java Vetiver' },
  { slug: 'javanol', name: 'Javanol' },
  { slug: 'juniper', name: 'Juniper' },
  { slug: 'juniper-needles', name: 'Juniper Needles' },
  { slug: 'labdanum', name: 'Labdanum' },
  { slug: 'laotian-oud', name: 'Laotian Oud' },
  { slug: 'laurel', name: 'Laurel' },
  { slug: 'lavender', name: 'Lavender' },
  { slug: 'lavender-leaves', name: 'Lavender Leaves' },
  { slug: 'leather', name: 'Leather' },
  { slug: 'lemon', name: 'Lemon' },
  { slug: 'lemon-verbena', name: 'Lemon Verbena' },
  { slug: 'licorice', name: 'Licorice' },
  { slug: 'light-woods', name: 'Light Woods' },
  { slug: 'lilac', name: 'Lilac' },
  { slug: 'lily-of-the-valley', name: 'Lily-of-the-Valley' },
  { slug: 'lime', name: 'Lime' },
  { slug: 'linden-blossom', name: 'Linden Blossom' },
  { slug: 'lipstick', name: 'Lipstick' },
  { slug: 'liqueur', name: 'Liqueur' },
  { slug: 'lotus', name: 'Lotus' },
  { slug: 'lychee', name: 'Lychee' },
  { slug: 'mace', name: 'Mace' },
  { slug: 'madagascar-vanilla', name: 'Madagascar Vanilla' },
  { slug: 'magnolia', name: 'Magnolia' },
  { slug: 'mahogany', name: 'Mahogany' },
  { slug: 'mahonial', name: 'Mahonial' },
  { slug: 'malabar-pepper', name: 'Malabar Pepper' },
  { slug: 'mallow', name: 'Mallow' },
  { slug: 'mango', name: 'Mango' },
  { slug: 'maple-syrup', name: 'Maple Syrup' },
  { slug: 'maplewood', name: 'Maplewood' },
  { slug: 'marigold', name: 'Marigold' },
  { slug: 'marine-notes', name: 'Marine Notes' },
  { slug: 'marshmallow', name: 'Marshmallow' },
  { slug: 'marzipan', name: 'Marzipan' },
  { slug: 'mastic', name: 'Mastic' },
  { slug: 'mediterranean-pine', name: 'Mediterranean Pine' },
  { slug: 'melon', name: 'Melon' },
  { slug: 'metallic-notes', name: 'Metallic Notes' },
  { slug: 'milk', name: 'Milk' },
  { slug: 'mimosa', name: 'Mimosa' },
  { slug: 'mineral-notes', name: 'Mineral Notes' },
  { slug: 'mint', name: 'Mint' },
  { slug: 'muguet', name: 'Muguet' },
  { slug: 'mugwort', name: 'Mugwort' },
  { slug: 'muscenone', name: 'Muscenone' },
  { slug: 'muscone', name: 'Muscone' },
  { slug: 'musk', name: 'Musk' },
  { slug: 'musk-ambrette', name: 'Musk-Ambrette' },
  { slug: 'myrrh', name: 'Myrrh' },
  { slug: 'myrtle', name: 'Myrtle' },
  { slug: 'mysore-sandalwood', name: 'Mysore Sandalwood' },
  { slug: 'narcisse', name: 'Narcissus' },
  { slug: 'neroli', name: 'Neroli' },
  { slug: 'nutella', name: 'Nutella' },
  { slug: 'nutmeg', name: 'Nutmeg' },
  { slug: 'nutty-notes', name: 'Nutty Notes' },
  { slug: 'nympheal', name: 'Nympheal' },
  { slug: 'oakmoss', name: 'Oakmoss' },
  { slug: 'oakwood', name: 'Oakwood' },
  { slug: 'olive-wood', name: 'Olive Wood' },
  { slug: 'oman-frankincense', name: 'Omani Frankincense' },
  { slug: 'opoponax', name: 'Opoponax' },
  { slug: 'orange', name: 'Orange' },
  { slug: 'orange-blossom', name: 'Orange Blossom' },
  { slug: 'orchid', name: 'Orchid' },
  { slug: 'orris', name: 'Orris' },
  { slug: 'osmanthus', name: 'Osmanthus' },
  { slug: 'other-musks', name: 'Other Musks' },
  { slug: 'oud', name: 'Oud' },
  { slug: 'palo-santo', name: 'Palo Santo' },
  { slug: 'paper', name: 'Paper' },
  { slug: 'papyrus', name: 'Papyrus' },
  { slug: 'paradisone', name: 'Paradisone' },
  { slug: 'passionfruit', name: 'Passionfruit' },
  { slug: 'patchouli', name: 'Patchouli' },
  { slug: 'peach', name: 'Peach' },
  { slug: 'pear', name: 'Pear' },
  { slug: 'peony', name: 'Peony' },
  { slug: 'peppermint', name: 'Peppermint' },
  { slug: 'peru-balsam', name: 'Peru Balsam' },
  { slug: 'petalia', name: 'Petalia' },
  { slug: 'petitgrain', name: 'Petitgrain' },
  { slug: 'pimento', name: 'Pimento' },
  { slug: 'pine', name: 'Pine' },
  { slug: 'pineapple', name: 'Pineapple' },
  { slug: 'pink-berries', name: 'Pink Berries' },
  { slug: 'pink-pepper', name: 'Pink Pepper' },
  { slug: 'pinyon-pine', name: 'Pinyon Pine' },
  { slug: 'pistachio', name: 'Pistachio' },
  { slug: 'plastic', name: 'Plastic' },
  { slug: 'plum', name: 'Plum' },
  { slug: 'pomelo', name: 'Pomelo' },
  { slug: 'popcorn', name: 'Popcorn' },
  { slug: 'powdery-notes', name: 'Powdery Notes' },
  { slug: 'praline', name: 'Praline' },
  { slug: 'precious-woods', name: 'Precious Woods' },
  { slug: 'quince', name: 'Quince' },
  { slug: 'rain-note', name: 'Rain Note' },
  { slug: 'raisin', name: 'Raisin' },
  { slug: 'rare-botanical', name: 'Rare Botanical' },
  { slug: 'raspberry', name: 'Raspberry' },
  { slug: 'red-tea', name: 'Red Tea' },
  { slug: 'redwood', name: 'Redwood' },
  { slug: 'resins', name: 'Resins' },
  { slug: 'rhubarb', name: 'Rhubarb' },
  { slug: 'rose', name: 'Rose' },
  { slug: 'rosemary', name: 'Rosemary' },
  { slug: 'rosewood', name: 'Rosewood' },
  { slug: 'rosyfolia', name: 'Rosyfolia' },
  { slug: 'rum', name: 'Rum' },
  { slug: 'saffron', name: 'Saffron' },
  { slug: 'sage', name: 'Sage' },
  { slug: 'sandalwood', name: 'Sandalwood' },
  { slug: 'sea-salt', name: 'Sea Salt' },
  { slug: 'seaweed', name: 'Seaweed' },
  { slug: 'sequoia-wood', name: 'Sequoia Wood' },
  { slug: 'sesame', name: 'Sesame' },
  { slug: 'siberian-pine', name: 'Siberian Pine' },
  { slug: 'sichuan-pepper', name: 'Sichuan Pepper' },
  { slug: 'smoke', name: 'Smoke' },
  { slug: 'snow-accord', name: 'Snow Accord' },
  { slug: 'solar-notes', name: 'Solar Notes' },
  { slug: 'somalian-frankincense', name: 'Somalian Frankincense' },
  { slug: 'spearmint', name: 'Spearmint' },
  { slug: 'spicy-notes', name: 'Spicy Notes' },
  { slug: 'star-anise', name: 'Star Anise' },
  { slug: 'strawberry', name: 'Strawberry' },
  { slug: 'styrax', name: 'Styrax' },
  { slug: 'suede', name: 'Suede' },
  { slug: 'sugar', name: 'Sugar' },
  { slug: 'synthetic-accord', name: 'Synthetic Accord' },
  { slug: 'tahitian-vanilla', name: 'Tahitian Vanilla' },
  { slug: 'taif-rose', name: 'Taif Rose' },
  { slug: 'tamarind', name: 'Tamarind' },
  { slug: 'tangerine', name: 'Tangerine' },
  { slug: 'teak', name: 'Teak' },
  { slug: 'thyme', name: 'Thyme' },
  { slug: 'tobacco', name: 'Tobacco' },
  { slug: 'toffee', name: 'Toffee' },
  { slug: 'tolu-balsam', name: 'Tolu Balsam' },
  { slug: 'tomato-leaf', name: 'Tomato Leaf' },
  { slug: 'tonka-bean', name: 'Tonka Bean' },
  { slug: 'tonkin-musk', name: 'Tonkin Musk' },
  { slug: 'treemoss', name: 'Treemoss' },
  { slug: 'truffle', name: 'Truffle' },
  { slug: 'tuberose', name: 'Tuberose' },
  { slug: 'tulip', name: 'Tulip' },
  { slug: 'turkish-rose', name: 'Turkish Rose' },
  { slug: 'turmeric', name: 'Turmeric' },
  { slug: 'vanilla', name: 'Vanilla' },
  { slug: 'vegan-castoreum', name: 'Vegan Castoreum' },
  { slug: 'vetiver', name: 'Vetiver' },
  { slug: 'vines', name: 'Vines' },
  { slug: 'violet', name: 'Violet' },
  { slug: 'violet-leaf', name: 'Violet Leaf' },
  { slug: 'walnut', name: 'Walnut' },
  { slug: 'water-note', name: 'Water Note' },
  { slug: 'whiskey', name: 'Whiskey' },
  { slug: 'white-amber', name: 'White Amber' },
  { slug: 'white-flowers', name: 'White Flowers' },
  { slug: 'white-musk', name: 'White Musk' },
  { slug: 'white-tea', name: 'White Tea' },
  { slug: 'wine', name: 'Wine' },
  { slug: 'wisteria', name: 'Wisteria' },
  { slug: 'woods', name: 'Woods' },
  { slug: 'ylang-ylang', name: 'Ylang-Ylang' },
  { slug: 'yuzu', name: 'Yuzu' },
];

const SLUGS = new Set(NOTE_LIBRARY.map((n) => n.slug));

// Common synonyms → library slug (matched on the normalized note name).
const ALIASES: Record<string, string> = {
  'damascus rose': 'bulgarian-rose',
  'damask rose': 'bulgarian-rose',
  'may rose': 'rose',
  'rose de mai': 'rose',
  agarwood: 'oud',
  oudh: 'oud',
  cedarwood: 'cedar',
  'virginia cedar': 'cedar',
  'atlas cedar': 'cedar',
  frankincense: 'incense',
  olibanum: 'incense',
  moss: 'oakmoss',
  'balsam fir': 'fir-balsam',
  tonka: 'tonka-bean',
  pepper: 'black-pepper',
  'woody notes': 'woods',
  wood: 'woods',
  'orange zest': 'orange',
  mandarin: 'orange',
  citrus: 'lemon',
  'juniper berries': 'juniper',
};

const normalize = (name: string) => name.trim().toLowerCase().replace(/\s+/g, ' ');

// Static image path for a built-in note, or null when the library has no match.
export function builtinNoteImage(name: string): string | null {
  const key = normalize(name);
  const slug = ALIASES[key] ?? key.replace(/ /g, '-');
  return SLUGS.has(slug) ? `/notes/${slug}.webp` : null;
}
